# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  db-cms:
    image: postgres:14
    restart: always
    container_name: cms-db
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: agir-cms
      POSTGRES_PASSWORD: agir-cms
      POSTGRES_DB: agir-cms
